//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesApp3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_lfgc
    {
        public int Id { get; set; }
        public string Talla { get; set; }
        public string Tipo { get; set; }
        public string Color { get; set; }
        public string Brand { get; set; }
        public string Provider { get; set; }
        public string Temporada { get; set; }
        public string Title { get; set; }
        public string Nombre { get; set; }
        public string Description { get; set; }
        public string Observations { get; set; }
        public Nullable<decimal> PriceDistributor { get; set; }
        public decimal PriceClient { get; set; }
        public decimal PriceMember { get; set; }
        public bool IsEnabled { get; set; }
        public string Keywords { get; set; }
        public System.DateTime DateUpdate { get; set; }
    }
}
